apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          hostPath:
            path: /ruta/a/tu/config/local
