apiVersion: v1
kind: Service
metadata:
  name: wireguard
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: ui
    - port: 51820
      targetPort: 51820
      protocol: UDP
      name: vpn
  selector:
    app: wireguard
